language: node_js

node_js:
  - 10

cache:
  npm: true
  directories:
    - ~/.cache

install: npm install

before_script:
  - npm run lint
  - npm run cy:verify

script: npm run build

after_script:
  - npm run serve -- --silent &
  - npm run cy:all -- --record --parallel
  - kill $(jobs -p) || true

before_deploy:
  - '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
  - npm install -g greenkeeper-lockfile
  - greenkeeper-lockfile-update

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: master
  local-dir: dist
  on:
    branch: develop
    node: 'node'

after_deploy: greenkeeper-lockfile-upload
