language: node_js
cache:
  directories:
  - node_modules
node_js:
  - 'node'
  - 'lts/*'
install: npm install
before_script:
  - npm run lint
script: npm run build
before_deploy:
  - '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
  - npm install -g greenkeeper-lockfile
  - greenkeeper-lockfile-update
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: master
  local-dir: dist
  on:
    branch: develop
after_deploy: greenkeeper-lockfile-upload
